services:
  - type: web
    name: krishnaraj-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyAejj2zMhFq1zP4V8FicFbcSKohggLfiyM
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /health